kind: pipeline
name: default

steps:
  - name: java-build
    pull: if-not-exists
    image: maven:3.8.4-openjdk-17
    commands:
      - mvn -DskipTests=true clean verify

  - name: sonar scan
    image: fmetais/drone-sonar-scan-plugin:latest
    settings:
      sonar.host.url: 
        from_secret: sonar_host
      sonar.login: 
        from_secret: sonar_token
      sonar.project-key: com.example:demo-java
      sonar.project-name: demo-java
      sonar.log.level: debug
      sonar.show-profiling: true
    commands:
      - mvn sonar:sonar
        
  - name: docker
    pull: if-not-exists
    image: plugins/docker
    settings:
      # registry: docker.io
      repo: annisaseptiani/drone-test
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - latest

trigger:
  branch:
    - master
