kind: pipeline
name: default

steps:
  - name: java-build
    pull: if-not-exists
    image: maven:3.8.4-openjdk-17
    commands:
      - mvn -DskipTests=true clean verify

  - name: java-unit-test
    pull: if-not-exists
    image: docker.io/maven:3.8.4-openjdk-17
    commands:
      - mvn jacoco:prepare-agent@preTest surefire:test jacoco:report@postTest

  - name: java-integration-test
    pull: if-not-exists
    image: docker.io/maven:3.8.4-openjdk-17
    commands:
      - mvn jacoco:prepare-agent-integration@preIT failsafe:integration-test jacoco:report-integration@postIT failsafe:verify

  - name: docker
    pull: if-not-exists
    image: plugins/docker
    settings:
      # registry: docker.io
      repo: annisaseptiani/drone-test
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - latest

trigger:
  branch:
    - master
