kind: pipeline
name: default

steps:
  - name: java-build
    pull: if-not-exists
    image: maven:3.8.4-openjdk-17
    commands:
      - mvn -DskipTests=true clean verify

  - name: sonar scan
    pull: if-not-exists
    image: aosapps/drone-sonar-plugin
    environment:
      sonar_host:
        from_secret: sonar_host
        sonar_token:
          from_secret: sonar_token
    commands:
      - sonar-scanner -Dsonar.projectKey=${DRONE_REPO}
        -Dsonar.projectName=${DRONE_REPO}
        -Dsonar.host.url=$sonar_host
        -Dsonar.login=$sonar_token
        -Dsonar.tests=src/test/java
        -Dsonar.sources=src/main/java
        -Dsonar.java.libraries=./target/classes
        -Dsonar.java.binaries=./target/classes
        
  - name: docker
    pull: if-not-exists
    image: plugins/docker
    settings:
      # registry: docker.io
      repo: annisaseptiani/drone-test
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - latest

trigger:
  branch:
    - master
